# Generated by Django 5.1.1 on 2024-10-01 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_image_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_users_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
