# Generated by Django 5.1.1 on 2024-10-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_comment_parent_comment_tweet_is_retweet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="user",
            name="following_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
