# Generated by Django 5.1.1 on 2024-10-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_tweet_likes_tweet_retweet_comment_tweet_retweets_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="likes",
            new_name="user_likes",
        ),
    ]
