# Generated by Django 5.1.1 on 2024-10-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_rename_likes_tweet_user_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="user_likes",
            new_name="users_liked",
        ),
    ]
