# Generated by Django 5.1.1 on 2024-10-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_rename_user_likes_tweet_users_liked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="retweet_comment",
        ),
    ]
