# Generated by Django 5.1.1 on 2025-03-15 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_tweet_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="retweets",
        ),
        migrations.AlterField(
            model_name="tweet",
            name="original_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets_original",
                to="user.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user_images/default.png",
                max_length=1000,
                null=True,
                upload_to="user_images/",
            ),
        ),
        migrations.CreateModel(
            name="Retweets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retweeted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retweets_by",
                        to="user.tweet",
                    ),
                ),
                (
                    "retweeted_tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retweets",
                        to="user.tweet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retweet",
                "verbose_name_plural": "Retweets",
                "ordering": ["-created_at"],
                "unique_together": {("retweeted_tweet", "retweeted_by")},
            },
        ),
    ]
