# Generated by Django 5.1.1 on 2025-03-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_options_remove_tweet_retweets_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="retweet_content",
        ),
    ]
