# Generated by Django 5.1.1 on 2025-03-15 04:37

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_remove_tweet_retweet_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                max_length=1000,
                null=True,
                upload_to=user.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.png",
                max_length=1000,
                null=True,
                upload_to=user.models.user_directory_path,
            ),
        ),
    ]
